ui:
  - changed-files:
      - any-glob-to-any-file:
          - "templates/**"
          - "static/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "CONTRIBUTING.md"
          - "CODE_OF_CONDUCT.md"
          - "docs/**"

data:
  - changed-files:
      - any-glob-to-any-file:
          - "data/**"

type:testing:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

type:accessibility:
  - changed-files:
      - any-glob-to-any-file:
          - "templates/**"
          - "static/**"

type:performance:
  - changed-files:
      - any-glob-to-any-file:
          - "utils/**"

type:security:
  - changed-files:
      - any-glob-to-any-file:
          - "utils/**"