name: Label PRs Based on Files

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Label PRs automatically
        uses: actions/labeler@v5

        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"